[package]
name = "gifed"
version = "0.2.0"
authors = ["gennyble <gen@nyble.dev>"]
edition = "2018"
license = "ISC"
description = "Gif encoding and decoding with fine control"
repository = "https://github.com/genuinebyte/gifed"

[dependencies]
weezl = "0.1.5"

[dev-dependencies]
rand = "0.8.5"
