[package]
name = "gifed"
version = "0.2.0"
authors = ["Genevieve <gen@nyble.dev>"]
edition = "2018"
license = "CC0-1.0"
description = "Gif encoding and decoding with fine control"
repository = "https://github.com/genuinebyte/gifed"

[dependencies]
weezl = "0.1.5"
