[package]
name = "gifed"
version = "0.3.0"
authors = ["gennyble <gen@nyble.dev>"]
edition = "2018"
license = "ISC"
description = "Gif encoding and decoding with fine control"
repository = "https://github.com/genuinebyte/gifed"

[dependencies]
bitvec = "1.0.1"
weezl = "0.1.5"

[features]
weezl-encode = []

[dev-dependencies]
rand = "0.8.5"
